### ISSUE TITLE
Status ?

### ISSUE THREAD

**Issue by deathart** [kjs6x2/WoWMoneyStatistics#7]
Hello, I particularly like this Addon and I find it unfortunate that it is no longer maintained for some years, will you ever update it? I took the liberty of making a modified version hoping that it does not bother you :) if it bothers you tell me and I will delete

**Comment by kjs6x2** [comment]
Making modifications to the addon does not bother me one bit.

As for getting the addon updated officially, I'll see what I can do; I haven't logged in to WoW in a long time.  Do your changes fix the issues the addon is having?  If so, feel free to do a pull request with your changes and I'll see about getting them officially released, if I can remember how to do that lol.

**Comment by kjs6x2** [comment]
New version of the addon is available that should work with DF.  Closing issue.
